export const FAVORITE_POKEMON_REQUEST = 'FAVORITE_POKEMON_REQUEST'
export const FAVORITE_POKEMON_SUCCESS = 'FAVORITE_POKEMON_SUCCESS'
export const FAVORITE_POKEMON_FAILURE = 'FAVORITE_POKEMON_FAILURE'
